// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: miin_Project

#ifndef _UI_COMP_GRP_TABLE_MODE_H
#define _UI_COMP_GRP_TABLE_MODE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Grp Table Mode
#define UI_COMP_GRP_TABLE_MODE_GRP_TABLE_MODE 0
#define UI_COMP_GRP_TABLE_MODE_LBLTABLEMODE0 1
#define UI_COMP_GRP_TABLE_MODE_LBLTABLEMODE1 2
#define UI_COMP_GRP_TABLE_MODE_LBLTABLEMODE2 3
#define UI_COMP_GRP_TABLE_MODE_LBLTABLEMODE3 4
#define UI_COMP_GRP_TABLE_MODE_LBLTABLEMODE4 5
#define _UI_COMP_GRP_TABLE_MODE_NUM 6
lv_obj_t *ui_Grp_Table_Mode_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
